apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ubuntu
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - image: kameneko/kubectl-all-in-one:latest
        name: kube-all-in-one
        command:
        - tail
        - -f
        - /dev/null
