apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubectl-all-in-one
  name: kubectl-all-in-one
spec:
  selector:
    matchLabels:
      app: kubectl-all-in-one
  template:
    metadata:
      labels:
        app: kubectl-all-in-one
    spec:
      containers:
      - image: kameneko/kubectl-all-in-one:latest
        name: kube-all-in-one
        command:
        - tail
        - -f
        - /dev/null
