apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: ubuntu
          image: kameneko/kubectl-all-in-one:latest
          command:
            - tail
            - -f
            - /dev/null
